- hosts: all
  remote_user: root

  tasks:
 - name: set pmd-cpu-mask
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: pmd-cpu-mask
      value: "{{ pmd-cpu-mask }}"

  - name: set dpdk-init
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-init
      value: true

  - name: set dpdk-socket-mem
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-socket-mem
      value: "{{ dpdk-socket-mem }}"

  - name: set dpdk lcore mask
    openvswitch_db:
      table: open_vswitch
      record: .
      col: other_config
      key: dpdk-lcore-mask
      value: "{{ dpdk-lcore-mask}}"

  - name: restart openvswitch service
    service:
      name: openvswitch
      state: restarted
